name: Upload model to DockerHub
on:
  workflow_dispatch:
  
jobs:
  upload_model_to_dockerhub:
    if: github.repository != 'ersilia-os/eos-template'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Checkout persist credentials
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
            
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install git+https://github.com/ersilia-os/ersilia.git
        
      - name: Upload model to dockerhub
        id: upload-model-to-dockerhub
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          source activate
          echo "Uploading model to dockerhub"
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/build_model_container_and_update_to_dockerhub.py
          python3 build_model_container_and_update_to_dockerhub.py $REPO_NAME $DOCKERHUB_USERNAME $DOCKERHUB_PASSWORD .
          rm build_model_container_and_update_to_dockerhub.py
